
$(document).ready(startApp);
var guess;
var randomNumber;
function startApp(){
	guess = new Guess();
	guess.guess_start();
	// randomNumber = new RandomGenerator( min, max);	
}

class Guess{
	constructor(){
		this.secretNumber;
		this.attachHandlers = this.attachHandlers.bind(this);
		this.handleGuess = this.handleGuess.bind(this);
		this.clearGuess = this.clearGuess.bind(this);
		this.randomNumber;
		console.log('attachHandle', this.attachHandlers)
	}
	guess_start(){
		this.secretNumber = this.pickRandomNumber(1,10);
		this.attachHandlers();
	}
	pickRandomNumber(min, max){
		this.randomNumber = new RandomGenerator( min, max);
		this.randomNumber.generate();
		console.log('pickrandomnum',this.randomNumber.generate());
	}
	attachHandlers(){
		$("#submitGuess").click( this.handleGuess );
		$("#userGuess").focus( this.clearGuess );
		console.log('attachHandle2', $("#submitGuess").click( this.handleGuess ))
	}
	handleGuess(){
		var userGuess = parseInt( $("#userGuess").val());
		if(userGuess<1 || userGuess>10){
			this.displayResult('invalid range.  Must be between 1 and 10');
			return;
		}
		if(userGuess === this.secretNumber){
			this.displayResult('you got it!');
			this.guess_start();
			this.reset();
		} else if (userGuess < this.secretNumber){
			this.displayResult('too low!');
		} else if (userGuess > this.secretNumber){
			this.displayResult('too high!');
		}
	}
	clearGuess(){
		$("#userGuess").val('');
	}
	displayResult( message ){
		$("#display").text( message );
	}
	reset(){
		// this.pickRandomNumber();
		this.clearGuess();
		this.guess_start();
	}
}

class RandomGenerator{
	constructor(min, max){ 
		//debugger;
		this.min = min;
		this.max = max;

		if (typeof this.min === "undefined"){
			this.min = 1;
		}
		if (typeof this.max === "undefined"){
			this.max = 10;
		}
		this.randomNumber;
		//takes in the minimum and maximum values
		//if they are not defined, it sets the minimum to 1, and the max to 10
		//makes storage for the random number
	}
	generate(){
		this.randomNumber = Math.floor(Math.random() * (this.max - this.min + 1) + this.min);
		console.log(this.randomNumber);
		return this.randomNumber;
		//make a random value between the minimum and maximum values
		//and store the number into the storage from the constructor
	}
	getRange(){
		return { min : this.min, max : this.max } 
		//return an object with min and max, min being the minimum value for the generator, max being the maximum value
		//returns a basic object literal
	}
	getNum(){
		return this.randomNumber;
		//return the random number that was generated by generate()
	}
}